version: '3.9'
services:
  lsmith:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./models-docker:/app/models
      - ./outputs:/app/outputs
      - ./venv:/app/venv
    environment:
      - COMMANDLINE_ARGS=
      - UVICORN_ARGS=--host 0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]